#!/usr/bin/env bash

FFMPEG_VERSION=4.4.1
FFMPEG_TARBALL=ffmpeg-$FFMPEG_VERSION.tar.bz2
FFMPEG_TARBALL_URL=http://ffmpeg.org/releases/$FFMPEG_TARBALL

LAME_VERSION=3.100
LAME_TARBALL=lame-$LAME_VERSION.tar.gz
LAME_TARBALL_URL=https://downloads.sourceforge.net/project/lame/lame/$LAME_VERSION/$LAME_TARBALL

FFMPEG_CONFIGURE_FLAGS=(
    --disable-shared
    --enable-static
    --enable-pic

    --disable-doc
    --disable-debug
    --disable-avdevice
    --disable-swscale
    --disable-programs
    --enable-rdft
    --enable-ffmpeg
    --enable-ffprobe
    --disable-network
    --disable-muxers
    --disable-demuxers
    --disable-zlib
    --disable-bzlib
    --disable-iconv
    --disable-bsfs
    --disable-filters
    --disable-parsers
    --disable-indevs
    --disable-outdevs
    --disable-encoders
    --disable-decoders
    --disable-hwaccels
    --disable-nvenc
    --disable-xvmc
    --disable-videotoolbox
    --disable-audiotoolbox

    --disable-protocols
    --enable-protocol=file
    --enable-protocol=pipe

    --enable-libmp3lame
    #--enable-libvorbis

    --enable-demuxer=aac
    --enable-demuxer=aiff
    --enable-demuxer=flac
    --enable-demuxer=mp3
    --enable-demuxer=ogg
    --enable-demuxer=wav
    --enable-demuxer=pcm_f64be
    --enable-demuxer=pcm_f64le
    --enable-demuxer=pcm_f32be
    --enable-demuxer=pcm_f32le
    --enable-demuxer=pcm_s32be
    --enable-demuxer=pcm_s32le
    --enable-demuxer=pcm_s24be
    --enable-demuxer=pcm_s24le
    --enable-demuxer=pcm_s16be
    --enable-demuxer=pcm_s16le
    --enable-demuxer=pcm_s8
    --enable-demuxer=pcm_u32be
    --enable-demuxer=pcm_u32le
    --enable-demuxer=pcm_u24be
    --enable-demuxer=pcm_u24le
    --enable-demuxer=pcm_u16be
    --enable-demuxer=pcm_u16le
    --enable-demuxer=pcm_u8

    --enable-decoder=aac
    --enable-decoder=flac
    --enable-decoder=mp3
    --enable-decoder=vorbis
    --enable-decoder=pcm_f32be
    --enable-decoder=pcm_f32le
    --enable-decoder=pcm_f64be
    --enable-decoder=pcm_f64le
    --enable-decoder=pcm_s8
    --enable-decoder=pcm_s16be
    --enable-decoder=pcm_s16le
    --enable-decoder=pcm_s24be
    --enable-decoder=pcm_s24le
    --enable-decoder=pcm_s32be
    --enable-decoder=pcm_s32le
    --enable-decoder=pcm_u8
    --enable-decoder=pcm_u16be
    --enable-decoder=pcm_u16le
    --enable-decoder=pcm_u24be
    --enable-decoder=pcm_u24le
    --enable-decoder=pcm_u32be
    --enable-decoder=pcm_u32le

    --enable-parser=aac
    --enable-parser=flac
    --enable-parser=vorbis

    --enable-muxer=aiff
    --enable-muxer=flac
    --enable-muxer=mp3
    --enable-muxer=ogg
    --enable-muxer=wav
    --enable-muxer=pcm_f32be
    --enable-muxer=pcm_f32le
    --enable-muxer=pcm_f64be
    --enable-muxer=pcm_f64le
    --enable-muxer=pcm_s16be
    --enable-muxer=pcm_s16le
    --enable-muxer=pcm_s24be
    --enable-muxer=pcm_s24le
    --enable-muxer=pcm_s32be
    --enable-muxer=pcm_s32le
    --enable-muxer=pcm_s8
    --enable-muxer=pcm_u16be
    --enable-muxer=pcm_u16le
    --enable-muxer=pcm_u24be
    --enable-muxer=pcm_u24le
    --enable-muxer=pcm_u32be
    --enable-muxer=pcm_u32le
    --enable-muxer=pcm_u8

    --enable-encoder=aac
    --enable-encoder=flac
    --enable-encoder=libmp3lame
    --enable-encoder=opus
    --enable-encoder=vorbis
    --enable-encoder=pcm_f32be
    --enable-encoder=pcm_f32le
    --enable-encoder=pcm_f64be
    --enable-encoder=pcm_f64le
    --enable-encoder=pcm_s16be
    --enable-encoder=pcm_s16le
    --enable-encoder=pcm_s24be
    --enable-encoder=pcm_s24le
    --enable-encoder=pcm_s32be
    --enable-encoder=pcm_s32le
    --enable-encoder=pcm_s64be
    --enable-encoder=pcm_s64le
    --enable-encoder=pcm_s8
    --enable-encoder=pcm_u16be
    --enable-encoder=pcm_u16le
    --enable-encoder=pcm_u24be
    --enable-encoder=pcm_u24le
    --enable-encoder=pcm_u32be
    --enable-encoder=pcm_u32le
    --enable-encoder=pcm_u8
)
